# define a version for the SDK

set(FLUX_SDK_VERSION_MAJOR 1)
set(FLUX_SDK_VERSION_MINOR 3)
set(FLUX_SDK_VERSION_PATCH 0)
set(FLUX_SDK_VERSION_TITLE "In Development")
set(FLUX_SDK_VERSION
    "${FLUX_SDK_VERSION_MAJOR}.${FLUX_SDK_VERSION_MINOR}.${FLUX_SDK_VERSION_PATCH} - ${FLUX_SDK_VERSION_TITLE}"
)
