name: Update Libraries

on:
  # - push
  pull_request:
  workflow_dispatch:

jobs:
  update-libraries:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Branch name
        run: echo update-libraries running on branch ${GITHUB_REF##*/}

      - name: Update the libraries
        run: |
          cd ./src/Spark/
          rm -f spDrivers.h
          touch spDrivers.h
          echo "#pragma once" > spDrivers.h
          find drivers -name "spDev*.h" | sed 's/^/#include "/;s/$/"/' >> spDrivers.h
          find drivers -name "spDev*.sh" -exec chmod +x {} \;
          find drivers -name "spDev*.sh" -exec {} \;

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:        
          message: 'update-libraries'
        
